// Generated by https://quicktype.io

export interface ActualCapacity {
    response:   Response;
    request:    Request;
    apiVersion: string;
}

export interface Request {
    command: string;
    params:  Params;
}

export interface Params {
    api_key: string;
    facets:  Facets;
    data:    string[];
    start:   string;
    end:     string;
}

export interface Facets {
    respondent: string[];
    fueltype:   string[];
}

export interface Response {
    "query execution":       number;
    "count query execution": number;
    total:                   number;
    dateFormat:              string;
    frequency:               string;
    data:                    Datum[];
    description:             string;
}

export interface Datum {
    period:            string;
    respondent:        string;
    "respondent-name": string;
    fueltype:          string;
    "type-name":       string;
    value:             number;
    "value-units":     string;
}

